//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "HuajiMapCorePlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface HuajiMapCorePlugin (SubHandler4)
- (NSDictionary<NSString*, Handler>*) getSubHandler4;
@end

NS_ASSUME_NONNULL_END
