// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:huaji_map_core/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';
import 'package:amap_search_fluttify/amap_search_fluttify.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';

class com_amap_api_maps_model_MVTTileOverlayOptions_Builder extends java_lang_Object  {
  //region constants
  static const String name__ = 'com.amap.api.maps.model.MVTTileOverlayOptions.Builder';

  @override
  final String tag__ = 'huaji_map_core';

  
  //endregion

  //region creators
  static Future<com_amap_api_maps_model_MVTTileOverlayOptions_Builder> create__() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod(
      'ObjectFactory::createcom_amap_api_maps_model_MVTTileOverlayOptions_Builder__',
    
    );
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__)!;
  }
  
  static Future<List<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>> create_batch__(int length) async {
    assert(true);
    final __result_batch__ = await  kAmapMapFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchcom_amap_api_maps_model_MVTTileOverlayOptions_Builder__',
      {'length': length}
    );
    return __result_batch__
        ?.map((it) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(it))
        .where((element) => element !=null)
        .cast<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>()
        .toList() ?? <com_amap_api_maps_model_MVTTileOverlayOptions_Builder>[];
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?> url(String? var1) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.amap.api.maps.model.MVTTileOverlayOptions.Builder@$refId::url([\'var1\':$var1])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::url', {"var1": var1, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__);
  }
  
  
  Future<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?> key(String? var1) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.amap.api.maps.model.MVTTileOverlayOptions.Builder@$refId::key([\'var1\':$var1])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::key', {"var1": var1, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__);
  }
  
  
  Future<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?> zIndex(double? var1) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.amap.api.maps.model.MVTTileOverlayOptions.Builder@$refId::zIndex([\'var1\':$var1])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::zIndex', {"var1": var1, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__);
  }
  
  
  Future<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?> visible(bool? var1) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.amap.api.maps.model.MVTTileOverlayOptions.Builder@$refId::visible([\'var1\':$var1])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::visible', {"var1": var1, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__);
  }
  
  
  Future<com_amap_api_maps_model_MVTTileOverlayOptions?> build() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: com.amap.api.maps.model.MVTTileOverlayOptions.Builder@$refId::build([])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::build', {"__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions>(__result__);
  }
  
  //endregion

  @override
  String toString() {
    return 'com_amap_api_maps_model_MVTTileOverlayOptions_Builder{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension com_amap_api_maps_model_MVTTileOverlayOptions_Builder_Batch on List<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?> {
  String? get refId {
    if (isEmpty) return null;
    return first?.refId;
  }

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<List<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>> url_batch(List<String?> var1) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::url_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"var1": var1[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__)).cast<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>().toList();
  }
  
  
  Future<List<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>> key_batch(List<String?> var1) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::key_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"var1": var1[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__)).cast<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>().toList();
  }
  
  
  Future<List<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>> zIndex_batch(List<double?> var1) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::zIndex_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"var1": var1[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__)).cast<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>().toList();
  }
  
  
  Future<List<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>> visible_batch(List<bool?> var1) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::visible_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"var1": var1[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions_Builder>(__result__)).cast<com_amap_api_maps_model_MVTTileOverlayOptions_Builder?>().toList();
  }
  
  
  Future<List<com_amap_api_maps_model_MVTTileOverlayOptions?>> build_batch() async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('com.amap.api.maps.model.MVTTileOverlayOptions.Builder::build_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_MVTTileOverlayOptions>(__result__)).cast<com_amap_api_maps_model_MVTTileOverlayOptions?>().toList();
  }
  
  //endregion
}