// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:huaji_map_core/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';
import 'package:amap_search_fluttify/amap_search_fluttify.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';

class MACircleRenderer extends MAOverlayPathRenderer  {
  //region constants
  static const String name__ = 'MACircleRenderer';

  @override
  final String tag__ = 'huaji_map_core';

  
  //endregion

  //region creators
  static Future<MACircleRenderer> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod(
      'ObjectFactory::createMACircleRenderer',
      {'init': init}
    );
    return AmapMapFluttifyIOSAs<MACircleRenderer>(__result__)!;
  }
  
  static Future<List<MACircleRenderer>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kAmapMapFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchMACircleRenderer',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => AmapMapFluttifyIOSAs<MACircleRenderer>(it))
        .where((element) => element !=null)
        .cast<MACircleRenderer>()
        .toList() ?? <MACircleRenderer>[];
  }
  
  //endregion

  //region getters
  Future<MACircle?> get_circle() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MACircleRenderer::get_circle", {'__this__': this});
    return AmapMapFluttifyIOSAs<MACircle>(__result__);
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<MACircleRenderer?> initWithCircle(MACircle? circle) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: MACircleRenderer@$refId::initWithCircle([])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('MACircleRenderer::initWithCircle', {"circle": circle, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyIOSAs<MACircleRenderer>(__result__);
  }
  
  //endregion

  @override
  String toString() {
    return 'MACircleRenderer{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension MACircleRenderer_Batch on List<MACircleRenderer?> {
  String? get refId {
    if (isEmpty) return null;
    return first?.refId;
  }

  //region getters
  Future<List<MACircle?>> get_circle_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MACircleRenderer::get_circle_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => AmapMapFluttifyIOSAs<MACircle>(__result__)).cast<MACircle?>().toList();
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<List<MACircleRenderer?>> initWithCircle_batch(List<MACircle?> circle) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('MACircleRenderer::initWithCircle_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"circle": circle[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyIOSAs<MACircleRenderer>(__result__)).cast<MACircleRenderer?>().toList();
  }
  
  //endregion
}