// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:huaji_map_core/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';
import 'package:amap_search_fluttify/amap_search_fluttify.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';

class MAParticleEmissionModuleOC extends NSObject  {
  //region constants
  static const String name__ = 'MAParticleEmissionModuleOC';

  @override
  final String tag__ = 'huaji_map_core';

  
  //endregion

  //region creators
  static Future<MAParticleEmissionModuleOC> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod(
      'ObjectFactory::createMAParticleEmissionModuleOC',
      {'init': init}
    );
    return AmapMapFluttifyIOSAs<MAParticleEmissionModuleOC>(__result__)!;
  }
  
  static Future<List<MAParticleEmissionModuleOC>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kAmapMapFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchMAParticleEmissionModuleOC',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => AmapMapFluttifyIOSAs<MAParticleEmissionModuleOC>(it))
        .where((element) => element !=null)
        .cast<MAParticleEmissionModuleOC>()
        .toList() ?? <MAParticleEmissionModuleOC>[];
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<MAParticleEmissionModuleOC?> initWithEmissionRate_rateTime(int? rate, int? rateTime) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: MAParticleEmissionModuleOC@$refId::initWithEmissionRate([\'rate\':$rate, \'rateTime\':$rateTime])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('MAParticleEmissionModuleOC::initWithEmissionRate_rateTime', {"rate": rate, "rateTime": rateTime, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyIOSAs<MAParticleEmissionModuleOC>(__result__);
  }
  
  //endregion

  @override
  String toString() {
    return 'MAParticleEmissionModuleOC{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension MAParticleEmissionModuleOC_Batch on List<MAParticleEmissionModuleOC?> {
  String? get refId {
    if (isEmpty) return null;
    return first?.refId;
  }

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<List<MAParticleEmissionModuleOC?>> initWithEmissionRate_rateTime_batch(List<int?> rate, List<int?> rateTime) async {
    assert(rate.length == rateTime.length);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('MAParticleEmissionModuleOC::initWithEmissionRate_rateTime_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"rate": rate[__i__], "rateTime": rateTime[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyIOSAs<MAParticleEmissionModuleOC>(__result__)).cast<MAParticleEmissionModuleOC?>().toList();
  }
  
  //endregion
}