// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:huaji_map_core/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';
import 'package:amap_search_fluttify/amap_search_fluttify.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';

class MATouchPoi extends NSObject  {
  //region constants
  static const String name__ = 'MATouchPoi';

  @override
  final String tag__ = 'huaji_map_core';

  
  //endregion

  //region creators
  static Future<MATouchPoi> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod(
      'ObjectFactory::createMATouchPoi',
      {'init': init}
    );
    return AmapMapFluttifyIOSAs<MATouchPoi>(__result__)!;
  }
  
  static Future<List<MATouchPoi>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kAmapMapFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchMATouchPoi',
      {'length': length, 'init': init}
    );
    return __result_batch__
        ?.map((it) => AmapMapFluttifyIOSAs<MATouchPoi>(it))
        .where((element) => element !=null)
        .cast<MATouchPoi>()
        .toList() ?? <MATouchPoi>[];
  }
  
  //endregion

  //region getters
  Future<String?> get_name() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MATouchPoi::get_name", {'__this__': this});
    return __result__;
  }
  
  Future<CLLocationCoordinate2D?> get_coordinate() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MATouchPoi::get_coordinate", {'__this__': this});
    return AmapMapFluttifyIOSAs<CLLocationCoordinate2D>(__result__);
  }
  
  Future<String?> get_uid() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MATouchPoi::get_uid", {'__this__': this});
    return __result__;
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'MATouchPoi{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension MATouchPoi_Batch on List<MATouchPoi?> {
  String? get refId {
    if (isEmpty) return null;
    return first?.refId;
  }

  //region getters
  Future<List<String?>> get_name_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MATouchPoi::get_name_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  Future<List<CLLocationCoordinate2D?>> get_coordinate_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MATouchPoi::get_coordinate_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => AmapMapFluttifyIOSAs<CLLocationCoordinate2D>(__result__)).cast<CLLocationCoordinate2D?>().toList();
  }
  
  Future<List<String?>> get_uid_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MATouchPoi::get_uid_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => __result__).cast<String?>().toList();
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}