// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:huaji_map_core/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';
import 'package:amap_search_fluttify/amap_search_fluttify.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';

class com_amap_api_maps_model_HeatmapTileProvider extends java_lang_Object with com_amap_api_maps_model_TileProvider {
  //region constants
  static const String name__ = 'com.amap.api.maps.model.HeatmapTileProvider';

  @override
  final String tag__ = 'huaji_map_core';

  static final int DEFAULT_RADIUS = 12;
  static final double DEFAULT_OPACITY = 0.6;
  //endregion

  //region creators
  
  //endregion

  //region getters
  static Future<com_amap_api_maps_model_Gradient?> get_static_DEFAULT_GRADIENT() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("com.amap.api.maps.model.HeatmapTileProvider::get_DEFAULT_GRADIENT", );
    return AmapMapFluttifyAndroidAs<com_amap_api_maps_model_Gradient>(__result__);
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'com_amap_api_maps_model_HeatmapTileProvider{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension com_amap_api_maps_model_HeatmapTileProvider_Batch on List<com_amap_api_maps_model_HeatmapTileProvider?> {
  String? get refId {
    if (isEmpty) return null;
    return first?.refId;
  }

  //region getters
  Future<List<com_amap_api_maps_model_Gradient?>> get_static_DEFAULT_GRADIENT_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("com.amap.api.maps.model.HeatmapTileProvider::get_DEFAULT_GRADIENT_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List).map((__result__) => AmapMapFluttifyAndroidAs<com_amap_api_maps_model_Gradient>(__result__)).cast<com_amap_api_maps_model_Gradient?>().toList();
  }
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}